- name: "Installing nginx"
  yum: name={{ item }} state=installed
  with_items:
  - nginx

- name: "copy configure file"
  template: src=../files/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - enable-nginx-config

- name: "start and enable"
  service: name=nginx state=started enabled=yes

- name: create /data/www
  file: path=/data/www state=directory mode=0755 group=nginx owner=nginx

- name: add index.php
  copy: src=tz.php dest=/data/www/tz.php
